In [78]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [79]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ITMO_PRO_ML_Course_1/6/candy-data.csv', sep=',')
df = df.set_index('competitorname')
df = df.drop(['Candy Corn', 'Nerds', 'Reeses stuffed with pieces'], axis = 0)
df.head()

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                       
100 Grand               1       0        1               0       0   
3 Musketeers            1       0        0               0       1   
One dime                0       0        0               0       0   
One quarter             0       0        0               0       0   
Air Heads               0       1        0               0       0   

                crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                        
100 Grand                      1     0    1         0         0.732   
3 Musketeers                   0     0    1         0         0.604   
One dime                       0     0    0         0         0.011   
One quarter                    0     0    0         0         0.011   
Air Heads                      0     0    0         0         0.906   

                pricepercent  winpercent  Y  
competitorname                               
100 Grand              0.860   66.971725  1  
3 Musketeers           0.511   67.602936  1  
One dime               0.116   32.261086  0  
One quarter            0.511   46.116505  0  
Air Heads              0.511   52.341465  1

In [80]:
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ITMO_PRO_ML_Course_1/6/candy-test.csv', sep=',')
df1 = df1.set_index('competitorname')
df1

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                                  
Sugar Babies                       0       1        1               0       0   
Sugar Daddy                        1       0        0               0       1   
Super Bubble                       0       1        0               0       0   
Swedish Fish                       0       1        0               0       0   
Tootsie Pop                        1       0        0               0       0   
Tootsie Roll Juniors               1       0        0               0       0   
Tootsie Roll Midgies               1       0        0               0       0   
Tootsie Roll Snack Bars            1       0        0               0       0   
Trolli Sour Bites                  0       1        0               0       0   
Twix                               0       1        0               0       0   
Twizzlers                          0       1        0               0       0   
Warheads                           0       1        0               0       0   
Welchs Fruit Snacks                0       1        0               0       0   
Werthers Original Caramel          1       0        1               0       0   
Whoppers                           1       0        0               0       0   

                           crispedricewafer  hard  bar  pluribus  \
competitorname                                                     
Sugar Babies                              0     1    0         1   
Sugar Daddy                               0     1    0         0   
Super Bubble                              0     0    0         0   
Swedish Fish                              0     0    0         1   
Tootsie Pop                               0     0    0         0   
Tootsie Roll Juniors                      0     0    0         0   
Tootsie Roll Midgies                      0     0    0         1   
Tootsie Roll Snack Bars                   0     0    1         0   
Trolli Sour Bites                         0     0    0         1   
Twix                                      0     0    0         0   
Twizzlers                                 0     0    0         0   
Warheads                                  0     1    0         0   
Welchs Fruit Snacks                       0     0    0         1   
Werthers Original Caramel                 0     1    0         0   
Whoppers                                  0     0    0         1   

                           sugarpercent  pricepercent  Y  
competitorname                                            
Sugar Babies                   0.647364       0.76700  0  
Sugar Daddy                    0.418000       0.32500  0  
Super Bubble                   0.162000       0.11600  0  
Swedish Fish                   0.604000       0.75500  1  
Tootsie Pop                    0.876560       0.56540  1  
Tootsie Roll Juniors           0.313000       0.51100  0  
Tootsie Roll Midgies           0.174000       0.01100  0  
Tootsie Roll Snack Bars        0.465000       0.32500  1  
Trolli Sour Bites              0.313000       0.25500  0  
Twix                           0.735430       0.86634  1  
Twizzlers                      0.220000       0.11600  0  
Warheads                       0.093000       0.11600  0  
Welchs Fruit Snacks            0.313000       0.31300  0  
Werthers Original Caramel      0.186000       0.26700  0  
Whoppers                       0.872000       0.84800  1

In [81]:
y_train = df['Y']
X_train = df.drop(columns=['winpercent','Y'])

y_test = df1['Y']
X_test = df1.drop(columns=['Y'])

topredict1 = df1.loc[['Tootsie Roll Juniors'],['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]
topredict2 = df1.loc[['Swedish Fish'],['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]


In [82]:
lr = LogisticRegression(random_state = 2019, solver = 'lbfgs').fit(X_train, y_train)

In [83]:
print(lr.predict(X_test))

[0 0 0 0 1 1 1 1 0 0 0 0 0 0 1]


In [90]:
print(lr.predict_proba(topredict1))
print(lr.predict_proba(topredict2))

[1]
[[0.63065897 0.36934103]]


In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, lr.predict(X_test))

0.7333333333333333

In [86]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, lr.predict(X_test))

array([[8, 2],
       [2, 3]])

In [87]:
from sklearn.metrics import recall_score
recall_score(y_test, lr.predict(X_test))

0.6

In [88]:
from sklearn.metrics import precision_score
precision_score(y_test, lr.predict(X_test))

0.6

In [89]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, lr.predict_proba(X_test)[:, 1])

0.8799999999999999